### ISSUE TITLE
Error regarding header_num_Of_vertical_stacking

### ISSUE THREAD

**Issue by ckaskouras** [jimioke/groupstackbar#2]
Hello,

I am trying to repliate the graph you jave produced but I receive the followin message when I try to run the function.
`local variable 'header_num_Of_vertical_stacking' referenced before assignment`

I tried to define the list before the loop (line 197) but still the same message appeared. 
Do you have any idea why this is happening?

Thank you
Christos

**Comment by abcnishant007** [comment]
Hi Christos, thanks for using our library! 

I just checked this, it is fine and generates the plots for me. 
May I know what OS are you on? We have tested for Mac and Ubuntu, but not for Windows. 

The problem might be in reading the csv on windows due to some delimeters. I can implement reading the csv file using pandas if you are using windows. Basically, this part should result in the file being read as a list of lists. 
https://github.com/jimioke/groupstackbar/blob/04c6b643c3b9d5957310f0680456f0f6b466b5db/groupstackbar.py#L183-L190 

Please confirm if you are using windows, then I can push a new version for `groupstackbar` that is compatible with windows.

**Comment by ckaskouras** [comment]
Thank you for your reply.

Yes, indeed I use windows

**Comment by abcnishant007** [comment]
Can you check this branch
https://github.com/jimioke/groupstackbar/tree/issue_2_csv_read?

If it works for you, I will merge it with the master

**Comment by ckaskouras** [comment]
It works fine!
Thank you

**Comment by abcnishant007** [comment]
perfect, I will merge this with the master

**Comment by abcnishant007** [comment]
@kusum-kumari please update the pip package whenever you have time. 
Also, I am logging another issue to automate the pip update automatically. That would be cool. I have seen some projects do that.
